### ISSUE TITLE
Einheit des Kondensators ist 12pf (picofarad)

### ISSUE THREAD

**Issue by harvey637** [AskSinPP/asksinpp.de#1]
Schönes Neues Jahr,

nur eine kleine Korrektur ... es sind nicht uf (µf) = MikroFarad, sonder pf = PicoFarad.
Allerdings gibt es auch keine so kleine Mikrofarads, und der Leser sollte vor solchen Änderungen 
schon etwas Respekt vor der Technik haben.

**Comment by psi-4ward** [comment]
Danke für den Hinweis!

Ich konnte ein paar Module mit diesen:
https://www.conrad.de/de/kemet-c0402c120j5gac7867-keramik-kondensator-smd-0402-12-pf-50-v-5-l-x-b-x-h-1-x-03-x-05-mm-1-st-1420326.html
wiederbeleben. 

Die Einheit ändere ich ab.

**Comment by psi-4ward** [comment]
5bbf210b3dee8db5f942e4ca5a0ee807176bce5f
