### ISSUE TITLE
HM-WDS40-TH-I-DHT22 Verknüpfung nur mit einem Thermostat möglich

### ISSUE THREAD

**Issue by drivin** [AskSinPP/asksinpp.de#4]
Ich habe mir einen Prototypen vom Typ HM-WDS40-TH-I-DHT22 aufgebaut.
Zunächst habe ich versucht den Prototypen mit einem HM-CC-RT-DN zu pairen. Dies scheint allerdings nur über eine Direktverknüpfung zu funktionieren - sprich zunächst die Zentrale pairen.
Nun habe ich versucht eine zweite Verknüpfung zu einem weiteren HM-CC-RT-DN anzulegen. Direkt per RPC sowie über den HM-Komponenten Konfigurator schien dies auch zu funktionieren. Allerdings bekommt nur der zuerst verknüpfte HM-CC-RT-DN Daten. Das zweite Thermostat beschwert sich über eine fehlende Verbindung (Funksymbol blinkt). Exemplarisch habe ich auch weitere Thermostate ausprobiert - immer mit dem gleichen Ergebnis.

Ist das Verhalten so bekannt oder gewünscht? Falls nein - wie lässt sich das Problem beheben?

**Comment by jp112sdl** [comment]
4 Dinge fallen mir da auf die Schnelle ein, die da reinspielen _(könnten)_:
- die Thermostate erwarten die Telegramme in einem exakten Zeitintervall. Das bekommst du nur hin, wenn du den Sketch auf RTC umbaust und die Hardware mit einem 32.786kHz Quarz betreibst
- der Sketch hat kein Wake-on-Radio implementiert; die Schaltung lässt sich also vom HKT aus nicht aufwachen, wenn es anklopft (Burst) und zwischendurch die Temperatur abfragen möchte
- es sind nicht alle Listen implementiert

> Allerdings bekommt nur der zuerst verknüpfte HM-CC-RT-DN Daten.

- du müsstest [hier](https://github.com/jp112sdl/Beispiel_AskSinPP/blob/d59f4ba6174db9d6d42977c49bd876c1c10f3bdf/examples/HM-WDS40-TH-I-DHT22/HM-WDS40-TH-I-DHT22.ino#L125) auf `broadcastPeerEvent` umstellen

Weitere Infos findest du evtl in dem Issue https://github.com/pa-pa/AskSinPP/issues/29

**Comment by drivin** [comment]
Ich habe bisher noch das 8MHz Quarz verbaut, habe aber vor ein paar Tagen im FHEM Forum einen Post von Pa-Pa gefunden, der genau die von dir thematisierte Problematik beschreibt. 
Bevor ich allerdings löten, werde ich deinen Tip mit broadcastPeerEvent umsetzen, da den Thermostaten scheinbar der "richtige" Sendezeitpunkt egal zu sein scheint. Kann natürlich auch sein, dass in dem einen noch Wake On Radio aktiviert ist. 
Ich prüfe die Geschichte die Tage und gebe Rückmeldung.

**Comment by jp112sdl** [comment]
> da den Thermostaten scheinbar der "richtige" Sendezeitpunkt egal zu sein scheint.

Hier mal reinschauen:
https://youtu.be/uAyzimU60jw?t=402

**Comment by drivin** [comment]
@jp112sdl, so wird ein Schuh draus. Es hört sich zumindest schlüssig an. Allerdings dürfte das erste Thermostat dann eigentlich keine oder nur ab und an Daten bekommen dürfen. Allerdings bekommt das tatsächlich zeitnah seine Daten.

Ich habe den Sketch eben auf broadcastPeerEvent umgestellt. Ich teste erst einmal. Andernfalls bestelle ich morgen ein wenig Kleinkram. Vermutlich wird das Porto teurer als die sieben Quarze.

**Comment by psi-4ward** [comment]
Ich konnte den Temperatursensor mit der HMSensor und einem 32kHz Oszillator aufbauen und mit einem HM-CC-RT-DN verknüpfen: https://forum.fhem.de/index.php/topic,20620.msg993912.html#msg993912

In absehbarer Zeit werde ich eine kleine Anleitung veröffentlichen
