### ISSUE TITLE
Projekt 'HomeMatic Gardena 9V Ventil'

### ISSUE THREAD

**Issue by sroettgermann** [AskSinPP/asksinpp.de#49]
Hallo!

Ich bin über das Homematic Forum auf das o. g. Projekt aufmerksam geworden.
https://homematic-forum.de/forum/viewtopic.php?f=76&t=49719

Es scheint als sei der Ersteller nicht mehr im Forum aktiv. 
@jp112sdl kannst du mir ggf. behilflich bei der Hardwarebeschaffung sein? Danke!

**Comment by Gelegenheitsbastler** [comment]
Hallo sroettgermann,

ich bin aktuell zwar nicht mehr sehr aktiv im Forum, aber per PN auf jeden Fall erreichbar. Das klappt auf jeden Fall einfacher als hier.

**Comment by jp112sdl** [comment]
Super, dann macht mal da (im Forum) weiter 👍
