### ISSUE TITLE
Lichtsensor auf Basis MAX44009

### ISSUE THREAD

**Issue by Fiiti** [AskSinPP/asksinpp.de#7]
Hi Jérôme,
auf Deiner Webseite schreibst Du ja, wenn etwas fehlt: her damit.
Ich vermisse einen reinen Helligkeits- / Lichtsensor. 
Du hast ja bei Deiner HB-UNI-Sen-WEA den Helligkeitssensor bereits verwendet.
Ich würde gerne den aber nur dediziert verwenden.

Wäre da was machbar? Kann ich irgendwie unterstützen?

Gruß,
Fiiti

**Comment by jp112sdl** [comment]
Hi, schau mal hier:
https://github.com/jp112sdl/Beispiel_AskSinPP/tree/master/examples/HM-Sen-LI-O

**Comment by Fiiti** [comment]
PRima, schaue ich mir an.
Und das geht dann auch mit der JP-HB-Devices-addon Bibliothek - oder muss ich noch irgendwas beachten?

Mein Sensor ist leider noch nicht gekommen, so kann ich es nicht einfach testen.

**Comment by jp112sdl** [comment]
Da es sich um ein natives HM-Gerät handelt, ist das Addon nicht notwendig.

**Comment by psi-4ward** [comment]
Ich denke die Fragen sind beantwortet?
